{
  "apiVersion": "v1",
  "kind": "Namespace",
  "metadata": {
    "name": "devops-assignment",
    "labels": {
      "name": "devops-assignment"
    }
  }
}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: devops-assignment
  labels:
    app: flask-uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-uploader
  template:
    metadata:
      labels:
        app: flask-uploader
    spec:
      containers:
      - name: uploader
        image: kentvilhelmsen/flask-app
        ports:
        - containerPort: 5000
